services:
  backend:
    build:
      context: ./
      dockerfile: dockerfile.app
    container_name: aes-backend
    environment:
      - NODE_ENV=PRODUCTION
      - HOST=0.0.0.0
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_API_URL=${AUTH_API_URL}
      - TOKEN_API_URL=${TOKEN_API_URL}
      - TENANT_ID=${TENANT_ID}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - SCOPE=${SCOPE}
      - SUBSCRIPTION_KEY=${SUBSCRIPTION_KEY}
    ports:
      - "8081:8080"
    networks:
      aes-network:
        ipv4_address: 172.28.5.4

networks:
  aes-network:
    driver: bridge
    external: true

volumes:
  postgres_data:
    name: aes-project_postgres_data
    external: true
