export enum PermissionEnum {
	CREATE = "CREATE",
	READ = "READ",
	UPDATE = "UPDATE",
	DELETE = "DELETE",
}

export enum StatusEnum {
	WORKING = "WORKING",
	INACTIVE = "INACTIVE",
	ON_LEAVE = "ON_LEAVE",
	CANCELLED = "CANCELLED",
	REJECTED = "REJECTED",
	CREATED = "CREATED",
	PENDING = "PENDING",
	ON_HOLD = "ON_HOLD",
	IN_PROGRESS = "IN_PROGRESS",
	PENDING_CONFIRM = "PENDING_CONFIRM",
	PENDING_APPROVAL = "PENDING_APPROVAL",
	PENDING_EDIT = "PENDING_EDIT",
	PENDING_REVIEW = "PENDING_REVIEW",
	COMPLETED = "COMPLETED",
}

export enum RoleEnum {
	ADMIN = "ADMIN",
	MANAGER = "MANAGER",
	SUB_MANAGER = "SUB_MANAGER",
	COMMANDER = "COMMANDER",
	SUB_COMMANDER = "SUB_COMMANDER",
	DEPARTMENT_HEAD = "DEPARTMENT_HEAD",
	ACCOUNTANT = "ACCOUNTANT",
	MAINTENANCE = "MAINTENANCE",
	UNIT_HEAD = "UNIT_HEAD",
	DRIVER = "DRIVER",
}
